import { ModuleItem } from "@/types/module";

export async function getModules(): Promise<ModuleItem[]> {
  return [
    {
      id: 1,
      title: "Mission",
      subtitle:
        "Define the mission and contextual framework of the educational institution",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 0, y: 0 },
    },
    {
      id: 2,
      title: "Super Maker",
      subtitle: "Hands-on learning, creativity, collaboration",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 1, y: 0 },
    },
    {
      id: 3,
      title: "Electives",
      subtitle: "STEM & Arts and Humanities",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 0, y: 0 },
    },
    {
      id: 4,
      title: "Boost",
      subtitle: "Support | Extra Help",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 1, y: 0 },
    },
    {
      id: 5,
      title: "COMP 3",
      subtitle: "Competence | Digital & AI Literacy",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 0, y: 0 },
    },
    {
      id: 6,
      title: "College Expo",
      subtitle: "Experience | Guidance",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 1, y: 0 },
    },
    {
      id: 7,
      title: "C.A.R.E.",
      subtitle: "Support & Wellbeing",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 0, y: 0 },
    },
    {
      id: 8,
      title: "Family Circle",
      subtitle: "Engagement, Family partnership",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 1, y: 0 },
    },
    {
      id: 9,
      title: "Science",
      subtitle: "Lab | Exploration | Projects",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 0, y: 0 },
    },
    {
      id: 10,
      title: "Math",
      subtitle: "Math mastery",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 1, y: 0 },
    },
    {
      id: 11,
      title: "COMP 3",
      subtitle: "Digital Literacy (Bottom)",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 0, y: 0 },
    },
    {
      id: 12,
      title: "Wayfinding & Cross Cutting Thinking",
      subtitle: "Navigation | Big picture",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 1, y: 0 },
    },
    {
      id: 13,
      title: "College Expo (Top)",
      subtitle: "Experience | Exposure",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 0, y: 0 },
    },
    {
      id: 14,
      title: "Student Wellbeing",
      subtitle: "Support structure for students",
      exp: 0,
      status: "active",
      description: "",
      category: "general",
      position: { x: 1, y: 0 },
    },
  ];
}
